/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.awt.Image;
import java.awt.Toolkit;
import javax.imageio.ImageIO;
/**
 *
 * @author kafas
 */
public class cvGuidedEdit_window extends javax.swing.JFrame {

    /**
     * Creates new form cvGuidedEdit_window
     */
    public cvGuidedEdit_window() {
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon3.png")));
        initComponents();
        initGeneralInfoComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        type1Tab = new javax.swing.JScrollPane();
        type1Tab.getVerticalScrollBar().setUnitIncrement(16);
        type1Panel = new javax.swing.JPanel();
        GENinfL = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        adressL = new javax.swing.JLabel();
        phoneL = new javax.swing.JLabel();
        emailL = new javax.swing.JLabel();
        mobileL = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        adressTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        mobileTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        professionalProfileL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        professionalProfileTextArea = new javax.swing.JTextArea();
        skilsAndExpL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        skillsAndExpTetxArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        careerSumaryL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        careerSumTextArea = new javax.swing.JTextArea();
        educationAndTraningL = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        educationAndTraningTextArea = new javax.swing.JTextArea();
        furtherCoursesL = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        furtherCoursesTextArea = new javax.swing.JTextArea();
        additionalInfoL = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        additionalInfoTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        interestsTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        type2Tab = new javax.swing.JScrollPane();
        type3Tab = new javax.swing.JScrollPane();
        backButton = new javax.swing.JButton();
        ProfileL = new javax.swing.JLabel();
        profileTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CV Editor: Process CV Guided");

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        type1Tab.setBorder(null);

        GENinfL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GENinfL.setText("1. GENERAL INFO");

        nameL.setText("NAME:");

        adressL.setText("ADRESS:");

        phoneL.setText("TELEPHONE:{HOME}");

        emailL.setText("EMAIL:");

        mobileL.setText("{MOBILE}");

        nameTextField.setEditable(false);
        nameTextField.setBorder(null);

        adressTextField.setEditable(false);
        adressTextField.setBorder(null);

        phoneTextField.setEditable(false);
        phoneTextField.setBorder(null);

        mobileTextField.setEditable(false);
        mobileTextField.setBorder(null);

        emailTextField.setEditable(false);
        emailTextField.setBorder(null);

        professionalProfileL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        professionalProfileL.setText("2. PROFESSIONAL PROFILE");

        professionalProfileTextArea.setColumns(20);
        professionalProfileTextArea.setRows(5);
        jScrollPane1.setViewportView(professionalProfileTextArea);

        skilsAndExpL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        skilsAndExpL.setText("3. SKILLS AND EXPERIENCE");

        skillsAndExpTetxArea.setColumns(20);
        skillsAndExpTetxArea.setRows(5);
        skillsAndExpTetxArea.setText("3.1 SKILLS AND EXPERIENCE ON <X>\n\n\n\n3.2 SKILLS AND EXPERIENCE ON <Y>\n\n\n\n3.3 SKILLS AND EXPERIENCE ON <Z>");
        jScrollPane2.setViewportView(skillsAndExpTetxArea);

        careerSumaryL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        careerSumaryL.setText("4. CAREER SUMMARY");

        careerSumTextArea.setColumns(20);
        careerSumTextArea.setRows(5);
        careerSumTextArea.setText("1. Company Name , Job Title, Date\n\n\n\n\n\n2. Company Name , Job Title, Date");
        careerSumTextArea.setMinimumSize(new java.awt.Dimension(260, 166));
        jScrollPane3.setViewportView(careerSumTextArea);

        educationAndTraningL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        educationAndTraningL.setText("5 EDUCATION AND TRAINING");

        educationAndTraningTextArea.setColumns(20);
        educationAndTraningTextArea.setRows(5);
        educationAndTraningTextArea.setText("1. Qualification, Establishment, Location, Date\n\n\n\n\n\n2. Qualification, Establishment, Location, Date");
        jScrollPane4.setViewportView(educationAndTraningTextArea);

        furtherCoursesL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        furtherCoursesL.setText("6 FURTHER COURSES");

        furtherCoursesTextArea.setColumns(20);
        furtherCoursesTextArea.setRows(5);
        furtherCoursesTextArea.setText("1. Qualification, Establishment, Location, Date\n\n\n\n\n\n2. Qualification, Establishment, Location, Date");
        jScrollPane5.setViewportView(furtherCoursesTextArea);

        additionalInfoL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        additionalInfoL.setText("7 ADDITIONAL INFORMATION");

        additionalInfoTextArea.setColumns(20);
        additionalInfoTextArea.setRows(5);
        jScrollPane6.setViewportView(additionalInfoTextArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("8 INTERESTS");

        interestsTextArea.setColumns(20);
        interestsTextArea.setRows(5);
        jScrollPane7.setViewportView(interestsTextArea);

        saveButton.setBackground(new java.awt.Color(204, 204, 204));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/saveIcon.jpg"))); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setIconTextGap(20);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout type1PanelLayout = new javax.swing.GroupLayout(type1Panel);
        type1Panel.setLayout(type1PanelLayout);
        type1PanelLayout.setHorizontalGroup(
            type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(type1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(type1PanelLayout.createSequentialGroup()
                        .addComponent(adressL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(type1PanelLayout.createSequentialGroup()
                        .addComponent(nameL)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(skilsAndExpL)
                    .addComponent(professionalProfileL)
                    .addGroup(type1PanelLayout.createSequentialGroup()
                        .addComponent(phoneL)
                        .addGap(18, 18, 18)
                        .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mobileL)
                        .addGap(18, 18, 18)
                        .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(careerSumaryL)
                    .addComponent(educationAndTraningL)
                    .addComponent(furtherCoursesL)
                    .addComponent(additionalInfoL)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(GENinfL)
                    .addComponent(jScrollPane7)
                    .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, type1PanelLayout.createSequentialGroup()
                            .addComponent(emailL)
                            .addGap(18, 18, 18)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveButton))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        type1PanelLayout.setVerticalGroup(
            type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(type1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GENinfL)
                .addGap(31, 31, 31)
                .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameL)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressL)
                    .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobileL)
                        .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneL)
                        .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(type1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailL)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professionalProfileL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(skilsAndExpL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(careerSumaryL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(educationAndTraningL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(furtherCoursesL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(additionalInfoL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        type1Tab.setViewportView(type1Panel);

        jTabbedPane1.addTab("Functional CV", type1Tab);
        jTabbedPane1.addTab("Chronological CV", type2Tab);
        jTabbedPane1.addTab("Combined CV", type3Tab);

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        ProfileL.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ProfileL.setText("Profile:");

        profileTextField.setEditable(false);
        profileTextField.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        profileTextField.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ProfileL, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1296, 1063));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        profile_window profWin = new profile_window();
        profWin.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cvGuidedEdit_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cvGuidedEdit_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cvGuidedEdit_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cvGuidedEdit_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cvGuidedEdit_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GENinfL;
    private javax.swing.JLabel ProfileL;
    private javax.swing.JLabel additionalInfoL;
    private javax.swing.JTextArea additionalInfoTextArea;
    private javax.swing.JLabel adressL;
    private javax.swing.JTextField adressTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea careerSumTextArea;
    private javax.swing.JLabel careerSumaryL;
    private javax.swing.JLabel educationAndTraningL;
    private javax.swing.JTextArea educationAndTraningTextArea;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel furtherCoursesL;
    private javax.swing.JTextArea furtherCoursesTextArea;
    private javax.swing.JTextArea interestsTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mobileL;
    private javax.swing.JTextField mobileTextField;
    private javax.swing.JLabel nameL;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneL;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel professionalProfileL;
    private javax.swing.JTextArea professionalProfileTextArea;
    private javax.swing.JTextField profileTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea skillsAndExpTetxArea;
    private javax.swing.JLabel skilsAndExpL;
    private javax.swing.JPanel type1Panel;
    private javax.swing.JScrollPane type1Tab;
    private javax.swing.JScrollPane type2Tab;
    private javax.swing.JScrollPane type3Tab;
    // End of variables declaration//GEN-END:variables

    //variable initiallization
    
    public void loadGeneralInfo(int id){
        profileTextField.setText(profile_window.users.get(id).profile_name);
        nameTextField.setText(profile_window.users.get(id).name);
        mobileTextField.setText(new Long(profile_window.users.get(id).mobile_number).toString());
        phoneTextField.setText(new Long(profile_window.users.get(id).phone_number).toString());
        adressTextField.setText(profile_window.users.get(id).adress);
        emailTextField.setText(profile_window.users.get(id).email);
    }
    
    public void initGeneralInfoComponents(){
        
    }
}
