/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kafas
 */
public class profile_window extends JFrame {

    /**
     * Creates new form profile_window
     */
    //selected profile
    private int sel;
        
    private static String user_name;
    private static String user_adress;
    private static String user_email;
    private static String user_profile_name;
    private static long user_phone_number;
    private static long user_mobile_number;
    public static ArrayList<user_credentials> users = new ArrayList<user_credentials>();
    private user_credentials user = new user_credentials();
    private DefaultListModel model;
    readUserProfiles readUser = new readUserProfiles();
    cvGuidedEdit_window editWin = new cvGuidedEdit_window();
    
    public user_credentials return_user_credentials(){
	user.name = user_name;
	user.adress = user_adress;
	user.email = user_email;
	user.phone_number = user_phone_number;
        user.profile_name = user_profile_name;
        user.mobile_number = user_mobile_number;
        users.add(user);
        return user;
    }
    
    //getter methods refer to textFields
    public static void get_user_name(String name){
	user_name = name;
    }
	
    public static void get_user_adress(String adress){
	user_adress = adress;
    }
	
    public static void get_user_email(String email){
    	user_email = email;
    }
	
    public static void get_user_phone(int phone){
	user_phone_number = phone;
    }
        
    public static void get_user_profile_name(String profile){
    	user_profile_name = profile;
    }
    
    public static void get_user_mobile_number(int mobile){
        user_mobile_number = mobile;
    }
    
    public profile_window() {
        initComponents();
        //adds elements to profile_list
        addProfilesToList();
    }
    
    public void addProfilesToList(){
        model = new DefaultListModel();
        readUser.readFrom();
        profile_list.setModel(model);
        for(int i=0; i<users.size(); i++){
            model.addElement(users.get(i).profile_name);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPanel = new javax.swing.JPanel();
        personalInfol = new javax.swing.JLabel();
        profileNamel = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        adressl = new javax.swing.JLabel();
        phoneNumberl = new javax.swing.JLabel();
        emaill = new javax.swing.JLabel();
        userProfileName = new javax.swing.JTextField();
        userNameField = new javax.swing.JTextField();
        userAdressField = new javax.swing.JTextField();
        userPhoneNumberField = new javax.swing.JTextField();
        userEmailField1 = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        load_profile_label = new javax.swing.JLabel();
        load_profile_scrpanel = new javax.swing.JScrollPane();
        profile_list = new javax.swing.JList<>();
        load_profile_button = new javax.swing.JButton();
        mobilel = new javax.swing.JLabel();
        userMobileNumber = new javax.swing.JTextField();
        deleteProfileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CV Editor: Profile");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        personalInfol.setText("Personal Info:");

        profileNamel.setText("PROFILE NAME: ");

        namel.setText("NAME: ");

        adressl.setText("ADRESS: ");

        phoneNumberl.setText("PHONE NUMBER:");

        emaill.setText("EMAIL:");

        userProfileName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userProfileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileNameActionPerformed(evt);
            }
        });

        userNameField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        userAdressField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userAdressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAdressFieldActionPerformed(evt);
            }
        });

        userPhoneNumberField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        userEmailField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        submitButton.setBackground(new java.awt.Color(204, 204, 204));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        load_profile_label.setText("Load Profile:");
        load_profile_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        profile_list.setBackground(new java.awt.Color(204, 204, 204));
        profile_list.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        profile_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        profile_list.setSelectionBackground(new java.awt.Color(0, 255, 255));
        profile_list.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                profile_listAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        profile_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_listMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_listMouseEntered(evt);
            }
        });
        load_profile_scrpanel.setViewportView(profile_list);

        load_profile_button.setBackground(new java.awt.Color(204, 204, 204));
        load_profile_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        load_profile_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/load.png"))); // NOI18N
        load_profile_button.setText("Load");
        load_profile_button.setIconTextGap(20);
        load_profile_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                load_profile_buttonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        load_profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_profile_buttonActionPerformed(evt);
            }
        });

        mobilel.setText("MOBILE PHONE:");

        userMobileNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userMobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMobileNumberActionPerformed(evt);
            }
        });

        deleteProfileButton.setBackground(new java.awt.Color(204, 204, 204));
        deleteProfileButton.setText("Delete");
        deleteProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(load_profile_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteProfileButton)
                .addGap(32, 32, 32))
            .addGroup(textPanelLayout.createSequentialGroup()
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(textPanelLayout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(personalInfol))
                        .addGroup(textPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namel)
                                .addComponent(profileNamel)
                                .addComponent(adressl))
                            .addGap(35, 35, 35)
                            .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userProfileName)
                                .addComponent(userNameField)
                                .addGroup(textPanelLayout.createSequentialGroup()
                                    .addComponent(userAdressField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(textPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phoneNumberl)
                                .addComponent(emaill))
                            .addGap(33, 33, 33)
                            .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userEmailField1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(userPhoneNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(userMobileNumber))))
                    .addGroup(textPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mobilel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(load_profile_scrpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPanelLayout.createSequentialGroup()
                        .addComponent(load_profile_label, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addGap(28, 28, 28))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalInfol)
                    .addComponent(load_profile_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textPanelLayout.createSequentialGroup()
                        .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileNamel))
                        .addGap(48, 48, 48)
                        .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namel)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adressl)
                            .addComponent(userAdressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberl)
                            .addComponent(userPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobilel)
                            .addComponent(userMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(load_profile_scrpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaill)
                    .addComponent(userEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(load_profile_button)
                    .addComponent(deleteProfileButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(641, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userProfileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userProfileNameActionPerformed

    private void userAdressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAdressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAdressFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try{
            correct_input(evt);
        }catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(profile_window.this,"PLEASE REENTER PHONE NUMBER"+ "\n"+"phone numbers consists of 10 digits");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void profile_listAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_profile_listAncestorAdded
          
    }//GEN-LAST:event_profile_listAncestorAdded

    private void load_profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_profile_buttonActionPerformed
        
        while(true){
            if(!profile_list.isSelectionEmpty()){
                sel = profile_list.getSelectedIndex();
                dispose();
                
                editWin.loadGeneralInfo(sel);
                editWin.setVisible(true);
                break;
            }else{
                JOptionPane.showMessageDialog(profile_window.this,"PLEASE SELECT A PROFILE FROM THE LIST");
                break;
            }
        }        
    }//GEN-LAST:event_load_profile_buttonActionPerformed

    private void load_profile_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_load_profile_buttonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_load_profile_buttonAncestorAdded

    private void userMobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMobileNumberActionPerformed

    private void deleteProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProfileButtonActionPerformed
       
        while(true){
            if(!profile_list.isSelectionEmpty()){
                sel = profile_list.getSelectedIndex();
                deleteProfile(users.get(sel).profile_name);
                break;
            }else{
                JOptionPane.showMessageDialog(profile_window.this,"PLEASE SELECT A PROFILE FROM THE LIST TO BE DELETED");
                break;
            }
        }     
    }//GEN-LAST:event_deleteProfileButtonActionPerformed

    private void profile_listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_listMouseEntered
        
    }//GEN-LAST:event_profile_listMouseEntered

    private void profile_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_listMouseClicked
        profile_selected(evt);
        
    }//GEN-LAST:event_profile_listMouseClicked
    private void profile_selected(MouseEvent e){
        if(!profile_list.isSelectionEmpty()){
            sel = profile_list.getSelectedIndex();
            displaySelectedProfile(sel);
        }
    }
    
    public void correct_input(ActionEvent e){
	String actionCommand = e.getActionCommand();
	if(actionCommand.equals("Submit")){
            checkForEmptyFields();
            getFieldText();
            
            
            //checks profile names for duplicates and alarms the user
            if(chechForDuplicates()){
                return;
            }
           
            //writes the new user to file
            WriteToFile writeTo = new WriteToFile();
            writeTo.writeToFile(user);
            
            //upadates profile_list
            addProfilesToList();
            
            //clear text fields after sumbiting
            clearProfile_windowTextFields();
        }
    }
    
    private void getFieldText(){
        get_user_profile_name(userProfileName.getText());
        get_user_name(userNameField.getText());
        get_user_adress(userAdressField.getText());
        get_user_email(userEmailField1.getText());
        get_user_phone(Integer.parseInt(userPhoneNumberField.getText()));
        get_user_mobile_number(Integer.parseInt(userMobileNumber.getText()));
    }
    
    private void checkForEmptyFields(){
        if(userNameField.getText().equals("")){
            JOptionPane.showMessageDialog(profile_window.this,"PLEASE FILL ALL THE FIELDS");
        }else if(userAdressField.getText().equals("")){
            JOptionPane.showMessageDialog(profile_window.this,"PLEASE FILL ALL THE FIELDS");
        }else if(userEmailField1.getText().equals("")){
            JOptionPane.showMessageDialog(profile_window.this,"PLEASE FILL ALL THE FIELDS");
        }else if(userProfileName.getText().equals("")){
              JOptionPane.showMessageDialog(profile_window.this,"PLEASE FILL ALL THE FIELDS");  
        }
    }
    
    private boolean chechForDuplicates(){
        for(int i=0; i<users.size(); i++){
            if((users.get(i).profile_name).equals(user_profile_name)){
                JOptionPane.showMessageDialog(profile_window.this,"Profile Name : '"+user_profile_name+"', already exists");
                userProfileName.setText("");
                return true;
            }
        }
        return_user_credentials();
        return false;
    }
    
    private void clearProfile_windowTextFields(){
        userNameField.setText("");
        userAdressField.setText("");
        userEmailField1.setText("");
        userPhoneNumberField.setText("");
        userMobileNumber.setText("");
        userProfileName.setText("");
    }
    
    private void deleteProfile(String profile){
        for(int i=0; i<users.size(); i++){
            if((users.get(i).profile_name).equals(profile)){
                //users.remove(i);
                model.remove(i);
                break;
            }
        }
    }
    
    private void displaySelectedProfile(int sel){
        userNameField.setText(users.get(sel).name);
        userAdressField.setText(users.get(sel).adress);
        userEmailField1.setText(users.get(sel).email);
        userPhoneNumberField.setText(new Long (users.get(sel).phone_number).toString());
        userMobileNumber.setText(new Long(users.get(sel).mobile_number).toString());
        userProfileName.setText(users.get(sel).profile_name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressl;
    private javax.swing.JButton deleteProfileButton;
    private javax.swing.JLabel emaill;
    private javax.swing.JButton load_profile_button;
    private javax.swing.JLabel load_profile_label;
    private javax.swing.JScrollPane load_profile_scrpanel;
    private javax.swing.JLabel mobilel;
    private javax.swing.JLabel namel;
    private javax.swing.JLabel personalInfol;
    private javax.swing.JLabel phoneNumberl;
    private javax.swing.JLabel profileNamel;
    private javax.swing.JList<String> profile_list;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel textPanel;
    private javax.swing.JTextField userAdressField;
    private javax.swing.JTextField userEmailField1;
    private javax.swing.JTextField userMobileNumber;
    private javax.swing.JTextField userNameField;
    private javax.swing.JTextField userPhoneNumberField;
    private javax.swing.JTextField userProfileName;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        welcome_window welWindow = new welcome_window();
        welWindow.setVisible(true);
    }
}